export type _CommonType = {
    "准考證號碼": string,
    "身分證號碼": string,
    "中文姓名": string ,
    "出生日期": string,
    "報簡職類": string,
    "英文姓名": string,
    "檢定區別": string,
    "通訊地址": string,
    "戶籍地址": string,
    "聯絡電話(住宅)": string,
    "聯絡電話(手機)": string,
    "就讀學校": string,
    "就讀科系": string,
    "上課別": string,
    "年級": string,
    "班級": string,
    "座號": string,
    "身分別": string,
    "學制": string,
}